apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xy8u92vvm-go
  janus-idp.io/tekton: xy8u92vvm-go
  backstage.io/kubernetes-id: xy8u92vvm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xy8u92vvm-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
